### ISSUE TITLE
Dear GTDef members

### ISSUE THREAD

**Issue by suribabud** [avnewman/GTDef#1]
Dear GTDef members,
I'm working in the intraplate region, how can i calculate the slip rate of a fault using geodetic (GPS) data?
Please help me.
Thank you.

**Comment by avnewman** [comment]
It would be good to look up the "Backslip" model for relating accumulated strain energy to faulting during the interseismic period (Savage, 1983).  For interseismic regions, however, this can be difficult.  In either case, the scientific development of such a problem is beyond the scope of the GTDef code repository.

**Comment by suribabud** [comment]
Thank you so much,
For suppose if we have an old earthquake in that particular fault (in intraplate), can we calculate the slip rate using older focal mechanism and GPS data?

Please suggest me.
Thank you.

**Comment by avnewman** [comment]
I’m sorry, but this is beyond the level of information  I can help with here.  This is beyond the scope of the repository, and there are many parameters to consider before one could make such an estimation.

**Comment by suribabud** [comment]
Ok. Thank you.
