### ISSUE TITLE
unit vector issue 

### ISSUE THREAD

**Issue by Elcappo2019** [avnewman/GTDef#2]
Dear GTdef_community,

 I am reaching out to express my appreciation for the valuable contributions you have made to the field of fault slip inversion modeling through GTdef.

I have recently started using GTdef for my fault slip inversion modeling work and have found it to be a powerful tool. However, I have encountered some challenges related to the "LOS vectors units" specified in the input file. 

 LOSdirE -------|
 LOSdirN        | - unit vector pointing from the ground toward the satellite (LOS direction)
 LOSdirV -------|

Specifically, I am using both Ascending and Descending Sentinel-1 datasets, and I have been unable to locate the required parameters in the official website of ESA or the metadata of SAR scenes.

How to obtain or determine the appropriate "LOS vectors units" for my Sentinel-1 dataset?
 I am curious to know if these parameters play a significant role in the accuracy of the output results. Any insights or suggestions you can offer would be immensely helpful.

**Comment by avnewman** [comment]
Yes, having appropriate and approximate orientation of the Line-of-Site (LOS) unit vector is vital for appropriate results, as this describes the orientation in which the deformation is being observed.  However, finding a precise value (actually set of values) is completely dependent on platform and terrain.

This is not an issue with GTDef.  We provide a mechanism to describe deformation relative to any arbitrary Line-of-Site (LOS) signal, whether it is an unwrapped SAR Interferogram, or unidirectional Electronic Distance Measurements (EDM) from a presumed fixed source.  

In our description, we give an explanation in terms of direction towards a satellite.  Getting the metadata to describe this is outside of the scope of the software itself.    To calculate an approximate LOS-unit vector for your scenes, you may look at the along track direction and information provided about the nominal incidence angle of observation for your scene.

As an example from some work we're doing in Rwanda.  We have a scene that was processed using the software GAMMA.  Within it is a file ending in `*.par` which includes a line that describes the incidence angle as **39.2117°**.

While there are likely better ways to do it, you can look at the georeferenced image from a scene to calculate the path and hence look direction in N and E components.  As an example, the below image shows the horizontal look angle to be **282°** CW from North given that it's a right looking descending satellite (N -> S) traveling at ~192° bearing.

Now that we have the orientations of the satellite look, we need to translate this into a unit vector of the ground pointing to the satellite.  Assuming a flat earth and an infinitely far satellite, we will assume the direction is constant across the scene.
1. Convert orientations to ground looking to sat.  The incidence is the same, however the  horizontal azimuth is now:
```
   HorizAngle = 282° - 180° = 102°
```
2. convert to a unit vector for each component.
   a. Vertical component:
```
      LosdirV = cos(incidence) = cos (39.2117°) = 0.7748
``` 
   b. Horizontal components:
```
       LosdirE = sin(incidence) * sin(HorizAngle) = sin(39.2117)*sin(102) = 0.6184
       LosdirN = sin(incidence) * cos(HorizAngle) = sin(39.2117)*cos(102) = -0.1314

```

![20210521_20210608_small_look](https://github.com/avnewman/GTDef/assets/11077577/ebe30144-3286-4656-8d0a-c7d20f28c40e)


Again.  The above is just an example for one situation.   More information about look directions and line-of-site can be found [here](https://satelliteblog.cgg.com/insar-line-of-sight-explained/).

**Comment by Elcappo2019** [comment]
Thank you for your kindly response @avnewman , But I have two criical points that I need to clarify them : -
1- When applying the recommended steps for processing the "Sentinel-1 dataset with ESA Snap software," I am still confused because there are different types of "Looking angles" (see attached image-1). Could you please advise me on which one I should choose?
2- When attempting to create a uniform slip model using the "ASC_local.in" input file that contains all the necessary parameters, I encountered a warning message (see attached image-2. when running the code. I am unsure whether this warning indicates an error or something else. Can you provide clarification on its [meaning?                                                    

![Image-1](https://github.com/avnewman/GTDef/assets/45139381/03c53bde-58e3-4db3-b500-baf2d2a05dff)
[ASC_input.txt](https://github.com/avnewman/GTDef/files/11784142/ASC_input.txt)
![image_2](https://github.com/avnewman/GTDef/assets/45139381/1b39cbce-98be-45a1-a195-c9c7e98ed796)

**Comment by avnewman** [comment]
I cannot comment on snap since I've never used it.  I'm not an expert in processing insar scenes.  You will need to look elsewhere for that.

That warning from GTdef is perfectly normal, and could have worked.  My only concern is that it stopped due to iterations and not model changes suggesting it may not have converged.
